export const NEXT_BALLS_COUNT = 3;
export const INITIAL_BALLS_COUNT = 5;
export const MIN_COLORS_COUNT = 5;
export const MAX_COLORS_COUNT = 9; // see colors array in ColoredCell.scss
export const DEFAULT_COLORS_COUNT = 7;
export const DEFAULT_SHOW_NEXT_COLORS = true;
export const DEFAULT_BOARD_SIZE = 9;
export const DEFAULT_LINE_LENGTH = 5;
export const HIGHEST_SCORES_LENGTH = 10;
export const INSTALL_PROMPT_INTERVAL_MS = 7 * 24 * 3600 * 1000;
