aliases:
  - &root-yarn |
    yarn install --non-interactive --cache-folder ~/.cache/yarn

  - &root-restore-yarn-cache
    keys:
      - root-yarn-{{ checksum "yarn.lock" }}-{{ .Environment.DOCKER_IMAGE }}
      # Fallback in case checksum fails
      - root-yarn-

  - &root-save-yarn-cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: root-yarn-{{ checksum "yarn.lock" }}-{{ .Environment.DOCKER_IMAGE }}

  - &filter-only-master
    branches:
      only:
        - master

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

defaults: &defaults
  working_directory: ~/boules
  docker:
    - image: circleci/node:12
      environment:
        DOCKER_IMAGE: node12

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore-cache: *root-restore-yarn-cache
      - run: *root-yarn
      - save-cache: *root-save-yarn-cache
      - run:
          name: run React app's tests
          command: yarn workspace react-app test

  build-react:
    <<: *defaults
    steps:
      - checkout
      - restore-cache: *root-restore-yarn-cache
      - run:
          name: build React app
          command: yarn workspace react-app build
      - persist_to_workspace:
          root: react-app
          paths:
            - build

  build-gh-pages:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Checkout gh-pages
          command: |
            git checkout gh-pages
            git rm -rf react-app
      - attach_workspace:
          at: react-app
      - run:
          name: Configure git user
          command: |
            git config user.email "jpatrzyk@users.noreply.github.com"
            git config user.name "Boules CI"
      - run:
          name: Push bundled react app to gh-pages branch
          command: |
            git add -A
            git diff-index --quiet HEAD || git commit -m "GH Pages"
            git push --set-upstream origin gh-pages

  build-windows:
    working_directory: ~/boules
    docker:
      - image: electronuserland/builder:wine
        environment:
          DOCKER_IMAGE: wine
    steps:
      - checkout
      - restore-cache: *root-restore-yarn-cache
      # this is a different docker image - thus, we cannot use cache or workspace from other jobs
      - run: *root-yarn
      - save-cache: *root-save-yarn-cache
      - run:
          name: build React app
          command: yarn workspace react-app build
      - run:
          name: build Electron app
          command: yarn workspace electron-app build
      - run:
          name: build distributable Windows app
          command: yarn workspace electron-app dist-pl --win
      - run:
          name: move artifacts
          command: |
            mkdir /tmp/artifacts;
            cp electron-app/release/*.exe /tmp/artifacts || :;
            cp electron-app/release/*.zip /tmp/artifacts || :;
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2

  test-and-build:
    jobs:
      - test:
          filters: *filter-ignore-gh-pages
      - build-react:
          requires:
            - test
          filters: *filter-ignore-gh-pages
      - build-gh-pages:
          requires:
            - build-react
          filters: *filter-only-master
      - build-windows:
          requires:
            - build-react
          filters: *filter-only-master
